console.log("animales")
console.log("gato")
console.log("perro")
console.log( "tortuga")
console.log("elefante")
console.log("perico")
console.log("leon")
console.log("rinoceronte")
console.log("venado " )
console.log( "luciernaga" )
console.log("tiburo")
console.log("ballena")
console.log("vaca")
